"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.retention_selector_metadata import RetentionSelectorMetadata


class TestRetentionSelectorMetadata(unittest.TestCase):
    """RetentionSelectorMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetentionSelectorMetadata(self):
        """Test RetentionSelectorMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RetentionSelectorMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
