# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harbor_client
from harbor_client.models.search_repository import SearchRepository  # noqa: E501
from harbor_client.rest import ApiException


class TestSearchRepository(unittest.TestCase):
    """SearchRepository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchRepository(self):
        """Test SearchRepository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor_client.models.search_repository.SearchRepository()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
