"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.chart_metadata import ChartMetadata
from harbor_client.model.chart_version_all_of import ChartVersionAllOf
from harbor_client.model.label import Label
globals()['ChartMetadata'] = ChartMetadata
globals()['ChartVersionAllOf'] = ChartVersionAllOf
globals()['Label'] = Label
from harbor_client.model.chart_version import ChartVersion


class TestChartVersion(unittest.TestCase):
    """ChartVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChartVersion(self):
        """Test ChartVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChartVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
