"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.project_deletable import ProjectDeletable


class TestProjectDeletable(unittest.TestCase):
    """ProjectDeletable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectDeletable(self):
        """Test ProjectDeletable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectDeletable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
