"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.retention_rule_param_metadata import RetentionRuleParamMetadata


class TestRetentionRuleParamMetadata(unittest.TestCase):
    """RetentionRuleParamMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetentionRuleParamMetadata(self):
        """Test RetentionRuleParamMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RetentionRuleParamMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
