"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.bool_config_item import BoolConfigItem
from harbor_client.model.configurations_scan_all_policy import ConfigurationsScanAllPolicy
from harbor_client.model.integer_config_item import IntegerConfigItem
from harbor_client.model.string_config_item import StringConfigItem
globals()['BoolConfigItem'] = BoolConfigItem
globals()['ConfigurationsScanAllPolicy'] = ConfigurationsScanAllPolicy
globals()['IntegerConfigItem'] = IntegerConfigItem
globals()['StringConfigItem'] = StringConfigItem
from harbor_client.model.configurations_response import ConfigurationsResponse


class TestConfigurationsResponse(unittest.TestCase):
    """ConfigurationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationsResponse(self):
        """Test ConfigurationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigurationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
