"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.retention_rule_metadata import RetentionRuleMetadata
from harbor_client.model.retention_selector_metadata import RetentionSelectorMetadata
globals()['RetentionRuleMetadata'] = RetentionRuleMetadata
globals()['RetentionSelectorMetadata'] = RetentionSelectorMetadata
from harbor_client.model.retention_metadata import RetentionMetadata


class TestRetentionMetadata(unittest.TestCase):
    """RetentionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetentionMetadata(self):
        """Test RetentionMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RetentionMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
