# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harbor_client
from harbor_client.api.icon_api import IconApi  # noqa: E501
from harbor_client.rest import ApiException


class TestIconApi(unittest.TestCase):
    """IconApi unit test stubs"""

    def setUp(self):
        self.api = api.icon_api.IconApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_icon(self):
        """Test case for get_icon

        Get artifact icon  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
