# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harbor_client
from harbor_client.api.preheat_api import PreheatApi  # noqa: E501
from harbor_client.rest import ApiException


class TestPreheatApi(unittest.TestCase):
    """PreheatApi unit test stubs"""

    def setUp(self):
        self.api = api.preheat_api.PreheatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_instance(self):
        """Test case for create_instance

        Create p2p provider instances  # noqa: E501
        """
        pass

    def test_create_policy(self):
        """Test case for create_policy

        Create a preheat policy under a project  # noqa: E501
        """
        pass

    def test_delete_instance(self):
        """Test case for delete_instance

        Delete the specified P2P provider instance  # noqa: E501
        """
        pass

    def test_delete_policy(self):
        """Test case for delete_policy

        Delete a preheat policy  # noqa: E501
        """
        pass

    def test_get_execution(self):
        """Test case for get_execution

        Get a execution detail by id  # noqa: E501
        """
        pass

    def test_get_instance(self):
        """Test case for get_instance

        Get a P2P provider instance  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        Get a preheat policy  # noqa: E501
        """
        pass

    def test_get_preheat_log(self):
        """Test case for get_preheat_log

        Get the log text stream of the specified task for the given execution  # noqa: E501
        """
        pass

    def test_list_executions(self):
        """Test case for list_executions

        List executions for the given policy  # noqa: E501
        """
        pass

    def test_list_instances(self):
        """Test case for list_instances

        List P2P provider instances  # noqa: E501
        """
        pass

    def test_list_policies(self):
        """Test case for list_policies

        List preheat policies  # noqa: E501
        """
        pass

    def test_list_providers(self):
        """Test case for list_providers

        List P2P providers  # noqa: E501
        """
        pass

    def test_list_providers_under_project(self):
        """Test case for list_providers_under_project

        Get all providers at project level  # noqa: E501
        """
        pass

    def test_list_tasks(self):
        """Test case for list_tasks

        List all the related tasks for the given execution  # noqa: E501
        """
        pass

    def test_manual_preheat(self):
        """Test case for manual_preheat

        Manual preheat  # noqa: E501
        """
        pass

    def test_ping_instances(self):
        """Test case for ping_instances

        Ping status of a instance.  # noqa: E501
        """
        pass

    def test_stop_execution(self):
        """Test case for stop_execution

        Stop a execution  # noqa: E501
        """
        pass

    def test_update_instance(self):
        """Test case for update_instance

        Update the specified P2P provider instance  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Update preheat policy  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
