"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor_client
from harbor_client.model.retention_policy_scope import RetentionPolicyScope
from harbor_client.model.retention_rule import RetentionRule
from harbor_client.model.retention_rule_trigger import RetentionRuleTrigger
globals()['RetentionPolicyScope'] = RetentionPolicyScope
globals()['RetentionRule'] = RetentionRule
globals()['RetentionRuleTrigger'] = RetentionRuleTrigger
from harbor_client.model.retention_policy import RetentionPolicy


class TestRetentionPolicy(unittest.TestCase):
    """RetentionPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetentionPolicy(self):
        """Test RetentionPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RetentionPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
