# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harbor_client
from api.project_metadata_api import ProjectMetadataApi  # noqa: E501
from harbor_client.rest import ApiException


class TestProjectMetadataApi(unittest.TestCase):
    """ProjectMetadataApi unit test stubs"""

    def setUp(self):
        self.api = api.project_metadata_api.ProjectMetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project_metadatas(self):
        """Test case for add_project_metadatas

        Add metadata for the specific project  # noqa: E501
        """
        pass

    def test_delete_project_metadata(self):
        """Test case for delete_project_metadata

        Delete the specific metadata for the specific project  # noqa: E501
        """
        pass

    def test_get_project_metadata(self):
        """Test case for get_project_metadata

        Get the specific metadata of the specific project  # noqa: E501
        """
        pass

    def test_list_project_metadatas(self):
        """Test case for list_project_metadatas

        Get the metadata of the specific project  # noqa: E501
        """
        pass

    def test_update_project_metadata(self):
        """Test case for update_project_metadata

        Update the specific metadata for the specific project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
