"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import harbor-client
from harbor-client.model.platform import Platform


class TestPlatform(unittest.TestCase):
    """Platform unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlatform(self):
        """Test Platform"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Platform()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
