"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from harbor_client.api_client import ApiClient, Endpoint as _Endpoint
from harbor_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from harbor_client.model.errors import Errors
from harbor_client.model.supported_webhook_event_types import SupportedWebhookEventTypes
from harbor_client.model.webhook_last_trigger import WebhookLastTrigger
from harbor_client.model.webhook_policy import WebhookPolicy


class WebhookApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __create_webhook_policy_of_project(
                self,
                project_name_or_id,
                webhook_policy,
                **kwargs
            ):
            """Create project webhook policy.  # noqa: E501

            This endpoint create a webhook policy if the project does not have one.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.create_webhook_policy_of_project(project_name_or_id, webhook_policy, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project
                webhook_policy (WebhookPolicy): Properties \"targets\" and \"event_types\" needed.

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            kwargs['webhook_policy'] = \
                    webhook_policy
            return self.call_with_http_info(**kwargs)

        self.create_webhook_policy_of_project = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/policies',
                'operation_id': 'create_webhook_policy_of_project',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'webhook_policy',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                    'webhook_policy',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'webhook_policy':
                        (WebhookPolicy,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'webhook_policy': 'body',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__create_webhook_policy_of_project
        )

        def __delete_webhook_policy_of_project(
                self,
                project_name_or_id,
                webhook_policy_id,
                **kwargs
            ):
            """Delete webhook policy of a project  # noqa: E501

            This endpoint is aimed to delete webhookpolicy of a project.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_webhook_policy_of_project(project_name_or_id, webhook_policy_id, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project
                webhook_policy_id (int): The ID of the webhook policy

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            kwargs['webhook_policy_id'] = \
                    webhook_policy_id
            return self.call_with_http_info(**kwargs)

        self.delete_webhook_policy_of_project = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}',
                'operation_id': 'delete_webhook_policy_of_project',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'webhook_policy_id',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                    'webhook_policy_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'webhook_policy_id':
                        (int,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'webhook_policy_id': 'webhook_policy_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'webhook_policy_id': 'path',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_webhook_policy_of_project
        )

        def __get_supported_event_types(
                self,
                project_name_or_id,
                **kwargs
            ):
            """Get supported event types and notify types.  # noqa: E501

            Get supportted event types and notify types.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_supported_event_types(project_name_or_id, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                SupportedWebhookEventTypes
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            return self.call_with_http_info(**kwargs)

        self.get_supported_event_types = _Endpoint(
            settings={
                'response_type': (SupportedWebhookEventTypes,),
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/events',
                'operation_id': 'get_supported_event_types',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_supported_event_types
        )

        def __get_webhook_policy_of_project(
                self,
                project_name_or_id,
                webhook_policy_id,
                **kwargs
            ):
            """Get project webhook policy  # noqa: E501

            This endpoint returns specified webhook policy of a project.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_webhook_policy_of_project(project_name_or_id, webhook_policy_id, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project
                webhook_policy_id (int): The ID of the webhook policy

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WebhookPolicy
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            kwargs['webhook_policy_id'] = \
                    webhook_policy_id
            return self.call_with_http_info(**kwargs)

        self.get_webhook_policy_of_project = _Endpoint(
            settings={
                'response_type': (WebhookPolicy,),
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}',
                'operation_id': 'get_webhook_policy_of_project',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'webhook_policy_id',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                    'webhook_policy_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'webhook_policy_id':
                        (int,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'webhook_policy_id': 'webhook_policy_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'webhook_policy_id': 'path',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_webhook_policy_of_project
        )

        def __last_trigger(
                self,
                project_name_or_id,
                **kwargs
            ):
            """Get project webhook policy last trigger info  # noqa: E501

            This endpoint returns last trigger information of project webhook policy.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.last_trigger(project_name_or_id, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [WebhookLastTrigger]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            return self.call_with_http_info(**kwargs)

        self.last_trigger = _Endpoint(
            settings={
                'response_type': ([WebhookLastTrigger],),
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/lasttrigger',
                'operation_id': 'last_trigger',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__last_trigger
        )

        def __list_webhook_policies_of_project(
                self,
                project_name_or_id,
                **kwargs
            ):
            """List project webhook policies.  # noqa: E501

            This endpoint returns webhook policies of a project.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_webhook_policies_of_project(project_name_or_id, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                sort (str): Sort the resource list in ascending or descending order. e.g. sort by field1 in ascending orderr and field2 in descending order with \"sort=field1,-field2\". [optional]
                q (str): Query string to query resources. Supported query patterns are \"exact match(k=v)\", \"fuzzy match(k=~v)\", \"range(k=[min~max])\", \"list with union releationship(k={v1 v2 v3})\" and \"list with intersetion relationship(k=(v1 v2 v3))\". The value of range and list can be string(enclosed by \" or '), integer or time(in format \"2020-04-09 02:36:00\"). All of these query patterns should be put in the query string \"q=xxx\" and splitted by \",\". e.g. q=k1=v1,k2=~v2,k3=[min~max]. [optional]
                page (int): The page number. [optional] if omitted the server will use the default value of 1
                page_size (int): The size of per page. [optional] if omitted the server will use the default value of 10
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [WebhookPolicy]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            return self.call_with_http_info(**kwargs)

        self.list_webhook_policies_of_project = _Endpoint(
            settings={
                'response_type': ([WebhookPolicy],),
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/policies',
                'operation_id': 'list_webhook_policies_of_project',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'x_request_id',
                    'x_is_resource_name',
                    'sort',
                    'q',
                    'page',
                    'page_size',
                ],
                'required': [
                    'project_name_or_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                    'page_size',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                    ('page_size',): {

                        'inclusive_maximum': 100,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                    'sort':
                        (str,),
                    'q':
                        (str,),
                    'page':
                        (int,),
                    'page_size':
                        (int,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                    'sort': 'sort',
                    'q': 'q',
                    'page': 'page',
                    'page_size': 'page_size',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                    'sort': 'query',
                    'q': 'query',
                    'page': 'query',
                    'page_size': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_webhook_policies_of_project
        )

        def __update_webhook_policy_of_project(
                self,
                project_name_or_id,
                webhook_policy_id,
                webhook_policy,
                **kwargs
            ):
            """Update webhook policy of a project.  # noqa: E501

            This endpoint is aimed to update the webhook policy of a project.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.update_webhook_policy_of_project(project_name_or_id, webhook_policy_id, webhook_policy, async_req=True)
            >>> result = thread.get()

            Args:
                project_name_or_id (str): The name or id of the project
                webhook_policy_id (int): The ID of the webhook policy
                webhook_policy (WebhookPolicy): All properties needed except \"id\", \"project_id\", \"creation_time\", \"update_time\".

            Keyword Args:
                x_request_id (str): An unique ID for the request. [optional]
                x_is_resource_name (bool): The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.. [optional] if omitted the server will use the default value of False
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get('_request_timeout')
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['project_name_or_id'] = \
                    project_name_or_id
            kwargs['webhook_policy_id'] = \
                    webhook_policy_id
            kwargs['webhook_policy'] = \
                    webhook_policy
            return self.call_with_http_info(**kwargs)

        self.update_webhook_policy_of_project = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basic'
                ],
                'endpoint_path': '/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}',
                'operation_id': 'update_webhook_policy_of_project',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'project_name_or_id',
                    'webhook_policy_id',
                    'webhook_policy',
                    'x_request_id',
                    'x_is_resource_name',
                ],
                'required': [
                    'project_name_or_id',
                    'webhook_policy_id',
                    'webhook_policy',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'x_request_id',
                ]
            },
            root_map={
                'validations': {
                    ('x_request_id',): {

                        'min_length': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'project_name_or_id':
                        (str,),
                    'webhook_policy_id':
                        (int,),
                    'webhook_policy':
                        (WebhookPolicy,),
                    'x_request_id':
                        (str,),
                    'x_is_resource_name':
                        (bool,),
                },
                'attribute_map': {
                    'project_name_or_id': 'project_name_or_id',
                    'webhook_policy_id': 'webhook_policy_id',
                    'x_request_id': 'X-Request-Id',
                    'x_is_resource_name': 'X-Is-Resource-Name',
                },
                'location_map': {
                    'project_name_or_id': 'path',
                    'webhook_policy_id': 'path',
                    'webhook_policy': 'body',
                    'x_request_id': 'header',
                    'x_is_resource_name': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__update_webhook_policy_of_project
        )
