# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harbor_client.configuration import Configuration


class ProjectSummaryQuota(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"hard": "ResourceList", "used": "ResourceList"}

    attribute_map = {"hard": "hard", "used": "used"}

    def __init__(self, hard=None, used=None, _configuration=None):  # noqa: E501
        """ProjectSummaryQuota - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hard = None
        self._used = None
        self.discriminator = None

        if hard is not None:
            self.hard = hard
        if used is not None:
            self.used = used

    @property
    def hard(self):
        """Gets the hard of this ProjectSummaryQuota.  # noqa: E501

        The hard limits of the quota  # noqa: E501

        :return: The hard of this ProjectSummaryQuota.  # noqa: E501
        :rtype: ResourceList
        """
        return self._hard

    @hard.setter
    def hard(self, hard):
        """Sets the hard of this ProjectSummaryQuota.

        The hard limits of the quota  # noqa: E501

        :param hard: The hard of this ProjectSummaryQuota.  # noqa: E501
        :type: ResourceList
        """

        self._hard = hard

    @property
    def used(self):
        """Gets the used of this ProjectSummaryQuota.  # noqa: E501

        The used status of the quota  # noqa: E501

        :return: The used of this ProjectSummaryQuota.  # noqa: E501
        :rtype: ResourceList
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this ProjectSummaryQuota.

        The used status of the quota  # noqa: E501

        :param used: The used of this ProjectSummaryQuota.  # noqa: E501
        :type: ResourceList
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ProjectSummaryQuota, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectSummaryQuota):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectSummaryQuota):
            return True

        return self.to_dict() != other.to_dict()
