# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harbor_client.configuration import Configuration


class ReplicationFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"type": "str", "value": "object", "decoration": "str"}

    attribute_map = {"type": "type", "value": "value", "decoration": "decoration"}

    def __init__(self, type=None, value=None, decoration=None, _configuration=None):  # noqa: E501
        """ReplicationFilter - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._type = None
        self._value = None
        self._decoration = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if decoration is not None:
            self.decoration = decoration

    @property
    def type(self):
        """Gets the type of this ReplicationFilter.  # noqa: E501

        The replication policy filter type.  # noqa: E501

        :return: The type of this ReplicationFilter.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ReplicationFilter.

        The replication policy filter type.  # noqa: E501

        :param type: The type of this ReplicationFilter.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this ReplicationFilter.  # noqa: E501

        The value of replication policy filter.  # noqa: E501

        :return: The value of this ReplicationFilter.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ReplicationFilter.

        The value of replication policy filter.  # noqa: E501

        :param value: The value of this ReplicationFilter.  # noqa: E501
        :type: object
        """

        self._value = value

    @property
    def decoration(self):
        """Gets the decoration of this ReplicationFilter.  # noqa: E501

        matches or excludes the result  # noqa: E501

        :return: The decoration of this ReplicationFilter.  # noqa: E501
        :rtype: str
        """
        return self._decoration

    @decoration.setter
    def decoration(self, decoration):
        """Sets the decoration of this ReplicationFilter.

        matches or excludes the result  # noqa: E501

        :param decoration: The decoration of this ReplicationFilter.  # noqa: E501
        :type: str
        """

        self._decoration = decoration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ReplicationFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReplicationFilter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReplicationFilter):
            return True

        return self.to_dict() != other.to_dict()
