# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harbor_client.configuration import Configuration


class WebhookPolicy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "id": "int",
        "name": "str",
        "description": "str",
        "project_id": "int",
        "targets": "list[WebhookTargetObject]",
        "event_types": "list[str]",
        "creator": "str",
        "creation_time": "datetime",
        "update_time": "datetime",
        "enabled": "bool",
    }

    attribute_map = {
        "id": "id",
        "name": "name",
        "description": "description",
        "project_id": "project_id",
        "targets": "targets",
        "event_types": "event_types",
        "creator": "creator",
        "creation_time": "creation_time",
        "update_time": "update_time",
        "enabled": "enabled",
    }

    def __init__(
        self,
        id=None,
        name=None,
        description=None,
        project_id=None,
        targets=None,
        event_types=None,
        creator=None,
        creation_time=None,
        update_time=None,
        enabled=None,
        _configuration=None,
    ):  # noqa: E501
        """WebhookPolicy - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._description = None
        self._project_id = None
        self._targets = None
        self._event_types = None
        self._creator = None
        self._creation_time = None
        self._update_time = None
        self._enabled = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if project_id is not None:
            self.project_id = project_id
        if targets is not None:
            self.targets = targets
        if event_types is not None:
            self.event_types = event_types
        if creator is not None:
            self.creator = creator
        if creation_time is not None:
            self.creation_time = creation_time
        if update_time is not None:
            self.update_time = update_time
        if enabled is not None:
            self.enabled = enabled

    @property
    def id(self):
        """Gets the id of this WebhookPolicy.  # noqa: E501

        The webhook policy ID.  # noqa: E501

        :return: The id of this WebhookPolicy.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WebhookPolicy.

        The webhook policy ID.  # noqa: E501

        :param id: The id of this WebhookPolicy.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this WebhookPolicy.  # noqa: E501

        The name of webhook policy.  # noqa: E501

        :return: The name of this WebhookPolicy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WebhookPolicy.

        The name of webhook policy.  # noqa: E501

        :param name: The name of this WebhookPolicy.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this WebhookPolicy.  # noqa: E501

        The description of webhook policy.  # noqa: E501

        :return: The description of this WebhookPolicy.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WebhookPolicy.

        The description of webhook policy.  # noqa: E501

        :param description: The description of this WebhookPolicy.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def project_id(self):
        """Gets the project_id of this WebhookPolicy.  # noqa: E501

        The project ID of webhook policy.  # noqa: E501

        :return: The project_id of this WebhookPolicy.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this WebhookPolicy.

        The project ID of webhook policy.  # noqa: E501

        :param project_id: The project_id of this WebhookPolicy.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def targets(self):
        """Gets the targets of this WebhookPolicy.  # noqa: E501


        :return: The targets of this WebhookPolicy.  # noqa: E501
        :rtype: list[WebhookTargetObject]
        """
        return self._targets

    @targets.setter
    def targets(self, targets):
        """Sets the targets of this WebhookPolicy.


        :param targets: The targets of this WebhookPolicy.  # noqa: E501
        :type: list[WebhookTargetObject]
        """

        self._targets = targets

    @property
    def event_types(self):
        """Gets the event_types of this WebhookPolicy.  # noqa: E501


        :return: The event_types of this WebhookPolicy.  # noqa: E501
        :rtype: list[str]
        """
        return self._event_types

    @event_types.setter
    def event_types(self, event_types):
        """Sets the event_types of this WebhookPolicy.


        :param event_types: The event_types of this WebhookPolicy.  # noqa: E501
        :type: list[str]
        """

        self._event_types = event_types

    @property
    def creator(self):
        """Gets the creator of this WebhookPolicy.  # noqa: E501

        The creator of the webhook policy.  # noqa: E501

        :return: The creator of this WebhookPolicy.  # noqa: E501
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this WebhookPolicy.

        The creator of the webhook policy.  # noqa: E501

        :param creator: The creator of this WebhookPolicy.  # noqa: E501
        :type: str
        """

        self._creator = creator

    @property
    def creation_time(self):
        """Gets the creation_time of this WebhookPolicy.  # noqa: E501

        The create time of the webhook policy.  # noqa: E501

        :return: The creation_time of this WebhookPolicy.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this WebhookPolicy.

        The create time of the webhook policy.  # noqa: E501

        :param creation_time: The creation_time of this WebhookPolicy.  # noqa: E501
        :type: datetime
        """

        self._creation_time = creation_time

    @property
    def update_time(self):
        """Gets the update_time of this WebhookPolicy.  # noqa: E501

        The update time of the webhook policy.  # noqa: E501

        :return: The update_time of this WebhookPolicy.  # noqa: E501
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this WebhookPolicy.

        The update time of the webhook policy.  # noqa: E501

        :param update_time: The update_time of this WebhookPolicy.  # noqa: E501
        :type: datetime
        """

        self._update_time = update_time

    @property
    def enabled(self):
        """Gets the enabled of this WebhookPolicy.  # noqa: E501

        Whether the webhook policy is enabled or not.  # noqa: E501

        :return: The enabled of this WebhookPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this WebhookPolicy.

        Whether the webhook policy is enabled or not.  # noqa: E501

        :param enabled: The enabled of this WebhookPolicy.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(WebhookPolicy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhookPolicy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WebhookPolicy):
            return True

        return self.to_dict() != other.to_dict()
