# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from harbor_client.api_client import ApiClient


class WebhookApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_webhook_policy_of_project(self, project_name_or_id, policy, **kwargs):  # noqa: E501
        """Create project webhook policy.  # noqa: E501

        This endpoint create a webhook policy if the project does not have one.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_webhook_policy_of_project(project_name_or_id, policy, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param WebhookPolicy policy: Properties \"targets\" and \"event_types\" needed. (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.create_webhook_policy_of_project_with_http_info(
                project_name_or_id, policy, **kwargs
            )  # noqa: E501
        else:
            (data) = self.create_webhook_policy_of_project_with_http_info(
                project_name_or_id, policy, **kwargs
            )  # noqa: E501
            return data

    def create_webhook_policy_of_project_with_http_info(
        self, project_name_or_id, policy, **kwargs
    ):  # noqa: E501
        """Create project webhook policy.  # noqa: E501

        This endpoint create a webhook policy if the project does not have one.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_webhook_policy_of_project_with_http_info(project_name_or_id, policy, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param WebhookPolicy policy: Properties \"targets\" and \"event_types\" needed. (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "project_name_or_id",
            "policy",
            "x_request_id",
            "x_is_resource_name",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_webhook_policy_of_project" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `create_webhook_policy_of_project`"
            )  # noqa: E501
        # verify the required parameter 'policy' is set
        if self.api_client.client_side_validation and (
            "policy" not in params or params["policy"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `policy` when calling `create_webhook_policy_of_project`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `create_webhook_policy_of_project`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if "policy" in params:
            body_params = params["policy"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/policies",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def delete_webhook_policy_of_project(
        self, project_name_or_id, webhook_policy_id, **kwargs
    ):  # noqa: E501
        """Delete webhook policy of a project  # noqa: E501

        This endpoint is aimed to delete webhookpolicy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_webhook_policy_of_project(project_name_or_id, webhook_policy_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.delete_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, **kwargs
            )  # noqa: E501
        else:
            (data) = self.delete_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, **kwargs
            )  # noqa: E501
            return data

    def delete_webhook_policy_of_project_with_http_info(
        self, project_name_or_id, webhook_policy_id, **kwargs
    ):  # noqa: E501
        """Delete webhook policy of a project  # noqa: E501

        This endpoint is aimed to delete webhookpolicy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_webhook_policy_of_project_with_http_info(project_name_or_id, webhook_policy_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "project_name_or_id",
            "webhook_policy_id",
            "x_request_id",
            "x_is_resource_name",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_webhook_policy_of_project" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `delete_webhook_policy_of_project`"
            )  # noqa: E501
        # verify the required parameter 'webhook_policy_id' is set
        if self.api_client.client_side_validation and (
            "webhook_policy_id" not in params or params["webhook_policy_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `webhook_policy_id` when calling `delete_webhook_policy_of_project`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `delete_webhook_policy_of_project`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501
        if "webhook_policy_id" in params:
            path_params["webhook_policy_id"] = params["webhook_policy_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_supported_event_types(self, project_name_or_id, **kwargs):  # noqa: E501
        """Get supported event types and notify types.  # noqa: E501

        Get supportted event types and notify types.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_supported_event_types(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: SupportedWebhookEventTypes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_supported_event_types_with_http_info(
                project_name_or_id, **kwargs
            )  # noqa: E501
        else:
            (data) = self.get_supported_event_types_with_http_info(
                project_name_or_id, **kwargs
            )  # noqa: E501
            return data

    def get_supported_event_types_with_http_info(self, project_name_or_id, **kwargs):  # noqa: E501
        """Get supported event types and notify types.  # noqa: E501

        Get supportted event types and notify types.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_supported_event_types_with_http_info(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: SupportedWebhookEventTypes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_name_or_id", "x_request_id", "x_is_resource_name"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_supported_event_types" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `get_supported_event_types`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `get_supported_event_types`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/events",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="SupportedWebhookEventTypes",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_webhook_policy_of_project(
        self, project_name_or_id, webhook_policy_id, **kwargs
    ):  # noqa: E501
        """Get project webhook policy  # noqa: E501

        This endpoint returns specified webhook policy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_webhook_policy_of_project(project_name_or_id, webhook_policy_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: WebhookPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, **kwargs
            )  # noqa: E501
        else:
            (data) = self.get_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, **kwargs
            )  # noqa: E501
            return data

    def get_webhook_policy_of_project_with_http_info(
        self, project_name_or_id, webhook_policy_id, **kwargs
    ):  # noqa: E501
        """Get project webhook policy  # noqa: E501

        This endpoint returns specified webhook policy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_webhook_policy_of_project_with_http_info(project_name_or_id, webhook_policy_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: WebhookPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "project_name_or_id",
            "webhook_policy_id",
            "x_request_id",
            "x_is_resource_name",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_webhook_policy_of_project" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `get_webhook_policy_of_project`"
            )  # noqa: E501
        # verify the required parameter 'webhook_policy_id' is set
        if self.api_client.client_side_validation and (
            "webhook_policy_id" not in params or params["webhook_policy_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `webhook_policy_id` when calling `get_webhook_policy_of_project`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `get_webhook_policy_of_project`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501
        if "webhook_policy_id" in params:
            path_params["webhook_policy_id"] = params["webhook_policy_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="WebhookPolicy",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def last_trigger(self, project_name_or_id, **kwargs):  # noqa: E501
        """Get project webhook policy last trigger info  # noqa: E501

        This endpoint returns last trigger information of project webhook policy.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_trigger(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: list[WebhookLastTrigger]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.last_trigger_with_http_info(project_name_or_id, **kwargs)  # noqa: E501
        else:
            (data) = self.last_trigger_with_http_info(project_name_or_id, **kwargs)  # noqa: E501
            return data

    def last_trigger_with_http_info(self, project_name_or_id, **kwargs):  # noqa: E501
        """Get project webhook policy last trigger info  # noqa: E501

        This endpoint returns last trigger information of project webhook policy.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_trigger_with_http_info(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: list[WebhookLastTrigger]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["project_name_or_id", "x_request_id", "x_is_resource_name"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method last_trigger" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `last_trigger`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `last_trigger`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/lasttrigger",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="list[WebhookLastTrigger]",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def list_webhook_policies_of_project(self, project_name_or_id, **kwargs):  # noqa: E501
        """List project webhook policies.  # noqa: E501

        This endpoint returns webhook policies of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_webhook_policies_of_project(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :param str sort: Sort the resource list in ascending or descending order. e.g. sort by field1 in ascending orderr and field2 in descending order with \"sort=field1,-field2\"
        :param str q: Query string to query resources. Supported query patterns are \"exact match(k=v)\", \"fuzzy match(k=~v)\", \"range(k=[min~max])\", \"list with union releationship(k={v1 v2 v3})\" and \"list with intersetion relationship(k=(v1 v2 v3))\". The value of range and list can be string(enclosed by \" or '), integer or time(in format \"2020-04-09 02:36:00\"). All of these query patterns should be put in the query string \"q=xxx\" and splitted by \",\". e.g. q=k1=v1,k2=~v2,k3=[min~max]
        :param int page: The page number
        :param int page_size: The size of per page
        :return: list[WebhookPolicy]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.list_webhook_policies_of_project_with_http_info(
                project_name_or_id, **kwargs
            )  # noqa: E501
        else:
            (data) = self.list_webhook_policies_of_project_with_http_info(
                project_name_or_id, **kwargs
            )  # noqa: E501
            return data

    def list_webhook_policies_of_project_with_http_info(
        self, project_name_or_id, **kwargs
    ):  # noqa: E501
        """List project webhook policies.  # noqa: E501

        This endpoint returns webhook policies of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_webhook_policies_of_project_with_http_info(project_name_or_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :param str sort: Sort the resource list in ascending or descending order. e.g. sort by field1 in ascending orderr and field2 in descending order with \"sort=field1,-field2\"
        :param str q: Query string to query resources. Supported query patterns are \"exact match(k=v)\", \"fuzzy match(k=~v)\", \"range(k=[min~max])\", \"list with union releationship(k={v1 v2 v3})\" and \"list with intersetion relationship(k=(v1 v2 v3))\". The value of range and list can be string(enclosed by \" or '), integer or time(in format \"2020-04-09 02:36:00\"). All of these query patterns should be put in the query string \"q=xxx\" and splitted by \",\". e.g. q=k1=v1,k2=~v2,k3=[min~max]
        :param int page: The page number
        :param int page_size: The size of per page
        :return: list[WebhookPolicy]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "project_name_or_id",
            "x_request_id",
            "x_is_resource_name",
            "sort",
            "q",
            "page",
            "page_size",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_webhook_policies_of_project" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `list_webhook_policies_of_project`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `list_webhook_policies_of_project`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if self.api_client.client_side_validation and (
            "page_size" in params and params["page_size"] > 100
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for parameter `page_size` when calling `list_webhook_policies_of_project`, must be a value less than or equal to `100`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501

        query_params = []
        if "sort" in params:
            query_params.append(("sort", params["sort"]))  # noqa: E501
        if "q" in params:
            query_params.append(("q", params["q"]))  # noqa: E501
        if "page" in params:
            query_params.append(("page", params["page"]))  # noqa: E501
        if "page_size" in params:
            query_params.append(("page_size", params["page_size"]))  # noqa: E501

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/policies",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="list[WebhookPolicy]",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def update_webhook_policy_of_project(
        self, project_name_or_id, webhook_policy_id, policy, **kwargs
    ):  # noqa: E501
        """Update webhook policy of a project.  # noqa: E501

        This endpoint is aimed to update the webhook policy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_webhook_policy_of_project(project_name_or_id, webhook_policy_id, policy, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param WebhookPolicy policy: All properties needed except \"id\", \"project_id\", \"creation_time\", \"update_time\". (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.update_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, policy, **kwargs
            )  # noqa: E501
        else:
            (data) = self.update_webhook_policy_of_project_with_http_info(
                project_name_or_id, webhook_policy_id, policy, **kwargs
            )  # noqa: E501
            return data

    def update_webhook_policy_of_project_with_http_info(
        self, project_name_or_id, webhook_policy_id, policy, **kwargs
    ):  # noqa: E501
        """Update webhook policy of a project.  # noqa: E501

        This endpoint is aimed to update the webhook policy of a project.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_webhook_policy_of_project_with_http_info(project_name_or_id, webhook_policy_id, policy, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_name_or_id: The name or id of the project (required)
        :param int webhook_policy_id: The ID of the webhook policy (required)
        :param WebhookPolicy policy: All properties needed except \"id\", \"project_id\", \"creation_time\", \"update_time\". (required)
        :param str x_request_id: An unique ID for the request
        :param bool x_is_resource_name: The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "project_name_or_id",
            "webhook_policy_id",
            "policy",
            "x_request_id",
            "x_is_resource_name",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_webhook_policy_of_project" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'project_name_or_id' is set
        if self.api_client.client_side_validation and (
            "project_name_or_id" not in params or params["project_name_or_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `project_name_or_id` when calling `update_webhook_policy_of_project`"
            )  # noqa: E501
        # verify the required parameter 'webhook_policy_id' is set
        if self.api_client.client_side_validation and (
            "webhook_policy_id" not in params or params["webhook_policy_id"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `webhook_policy_id` when calling `update_webhook_policy_of_project`"
            )  # noqa: E501
        # verify the required parameter 'policy' is set
        if self.api_client.client_side_validation and (
            "policy" not in params or params["policy"] is None
        ):  # noqa: E501
            raise ValueError(
                "Missing the required parameter `policy` when calling `update_webhook_policy_of_project`"
            )  # noqa: E501

        if self.api_client.client_side_validation and (
            "x_request_id" in params and len(params["x_request_id"]) < 1
        ):
            raise ValueError(
                "Invalid value for parameter `x_request_id` when calling `update_webhook_policy_of_project`, length must be greater than or equal to `1`"
            )  # noqa: E501
        collection_formats = {}

        path_params = {}
        if "project_name_or_id" in params:
            path_params["project_name_or_id"] = params["project_name_or_id"]  # noqa: E501
        if "webhook_policy_id" in params:
            path_params["webhook_policy_id"] = params["webhook_policy_id"]  # noqa: E501

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-Id"] = params["x_request_id"]  # noqa: E501
        if "x_is_resource_name" in params:
            header_params["X-Is-Resource-Name"] = params["x_is_resource_name"]  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if "policy" in params:
            body_params = params["policy"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = ["basic"]  # noqa: E501

        return self.api_client.call_api(
            "/projects/{project_name_or_id}/webhook/policies/{webhook_policy_id}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
