name: Generate documentation

on:
  workflow_dispatch
jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: docgen
      run: |
        ls -l
        git clone https://github.com/swagger-api/swagger-codegen
        ls -l
        cd swagger-codegen
        git checkout 5d4f6db5aeb2c47856aa75dfb2bf579891a3a44b
        wget https://raw.githubusercontent.com/container-registry/harbor-api-client/master/0001-Customize-templates.patch
        git config --global user.email "development.s004k@simplelogin.com"
        git config --global user.name "Github action"
        git am 0001-Customize-templates.patch
        echo "Compile converter..."
        mvn --version
        mvn --batch-mode package
        
        echo "Fetch swagger.yaml file"
        wget https://raw.githubusercontent.com/container-registry/harbor-api-client/master/swagger.yaml
        
        ls -l

        echo "Generate documentation..."
        java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
        --additional-properties projectName=harbor_client \
        --additional-properties packageVersion=2.7.0 \
        --additional-properties gitUserId=container-registry \
        --additional-properties gitRepoId=harbor-python-client-api \
        --git-user-id container-registry \
        --git-repo-id harbor-api-client \
        --additional-properties packageName=harbor_client \
        --additional-properties isOauth=true \
        --api-package api \
        --input-spec swagger.yaml \
        --lang python \
        --output harbor_client
        
        touch harbor_client/api/_index.md
        echo """
        ---
        title: "API"
        description: 'Documentation for Harbor API'
        date:  $(date +"%Y-%m-%d")
        draft: false
        layout: "single"
        weight: 1
        ---
        """ > harbor_client/api/_index.md

        touch harbor_client/model/_index.md
        echo """
        ---
        title: "Models"
        description: 'Documentation for Harbor models'
        date: $(date +"%Y-%m-%d")
        draft: false
        layout: "single"
        weight: 1
        ---
        """ > harbor_client/model/_index.md
        
        cat harbor_client/model/_index.md
        ls -l ../
        ls -l harbor_client
        pwd
        tar -czvf harbor-api-documentation.tar.gz harbor_client
        cp -f harbor-api-documentation.tar.gz ../archives/harbor-api-documentation.tar.gz
        pwd
        ls -l
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Alexandre Krispin
        author_email: development.s004k@simplelogin.com
        message: 'Update documentation'
        add: '../archive'
#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@latest
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#       with:
#         tag_name: ${{ github.ref_name }}
#         release_name: Release ${{ github.ref_name }}
#         body: |
#           Changes in this Release
#           - First Change
#           - Second Change
#         draft: false
#         prerelease: false
#     - name: Upload archive on release
#       run: gh release upload ${{ github.ref_name }} ../archives/harbor-api-client-documentation.tar.gz
#     - uses: ncipollo/release-action@v1
#       with:
#         artifacts: "harbor-api-client-doc.tar.gz,harbor_client/"





