name: Generate documentation

on:
  workflow_dispatch
jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: docgen
      run: |
        ls -l
        git clone https://github.com/swagger-api/swagger-codegen
        wget https://raw.githubusercontent.com/container-registry/harbor-api-client/master/swagger.yaml
        ls -l
        cd swagger-codegen
        git checkout 5d4f6db5aeb2c47856aa75dfb2bf579891a3a44b
        echo "Compile converter..."
        mvn --batch-mode package

        echo "Generate documentation..."
        java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
        --additional-properties projectName=harbor_client \
        --additional-properties packageVersion=2.7.0 \
        --additional-properties gitUserId=container-registry \
        --additional-properties gitRepoId=harbor-python-client-api \
        --git-user-id container-registry \
        --git-repo-id harbor-api-client \
        --additional-properties packageName=harbor_client \
        --additional-properties isOauth=true \
        --api-package api \
        --input-spec swagger.yaml \
        --lang python \
        --output harbor_client

        echo """
        ---
        title: "API"
        description: 'Documentation for Harbor API'
        date: 2022-27-12
        draft: false
        layout: "single"
        weight: 1
        ---
        """ > harbor_client/api/_index.md








